In [28]:
import tabula

In [29]:
lista_tabelas2 = tabula.read_pdf("ResultadoVale.pdf", pages="10")
print(len(lista_tabelas))

1

In [30]:
tabela = lista_tabelas2[0]
tabela.columns = tabela.iloc[0]
display(tabela)

,R$ milhões,NaN,NaN,NaN,Variação percentual
0,R$ milhões,NaN,NaN,NaN,Variação percentual
1,NaN,1T21,4T20,1T20,1T21/4T20 1T21/1T20
2,"Receita de vendas, líquida",69.301,78.938,31.251,"-12,2% 121,8%"
3,Custos e despesas,(27.359),(35.434),(21.619),"-22,8% 26,6%"
4,Despesas relacionadas a Brumadinho,(637),(25.002),(708),"-97,5% -10,0%"
5,EBIT (LAJIR) ajustado,41.729,18.987,9.248,"119,8% 351,2%"
6,Margem EBIT ajustado (%),"60,2%","24,1%","29,6%","150,3% 103,5%"
7,EBITDA (LAJIDA) ajustado,45.741,23.492,12.924,"94,7% 253,9%"
8,Lucro líquido atribuído aos acionistas da Vale,30.564,4.825,984,"533,5% n.m."
9,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN
11,Reconciliação LAJIDA,NaN,NaN,NaN,NaN
12,R$ milhões,NaN,1T21,NaN,4T20 1T20
13,Lucro líquido atribuído aos acionistas da Vale,NaN,30.564,NaN,4.825 984
14,Prejuízo atribuído aos acionistas não controla...,NaN,(375),NaN,(508) (347)
15,Lucro líquido,NaN,30.189,NaN,4.317 637
16,"Depreciação, exaustão e amortização",NaN,4.012,NaN,4.505 3.676
17,Tributos sobre lucro,NaN,9.950,NaN,1.014 (3.102)
18,Resultado financeiro,NaN,176,NaN,3.683 10.486
19,LAJIDA (EBITDA),NaN,44.327,13.519,11.697
20,Itens para reconciliação de LAJIDA (EBITDA) aj...,NaN,NaN,NaN,NaN
21,Redução ao valor recuperável e baixa de ativos...,NaN,NaN,NaN,NaN
22,NaN,NaN,897,NaN,7.815 136
23,circulantes,NaN,NaN,NaN,NaN
24,Resultado de participações e outros resultados...,NaN,NaN,NaN,NaN
25,NaN,NaN,93,NaN,1.673 767
26,e joint ventures,NaN,NaN,NaN,NaN
27,Dividendos recebidos e juros de coligadas e jo...,NaN,424,NaN,485 324
28,LAJIDA (EBITDA) ajustado,NaN,45.741,23.492,12.924

In [31]:
tabela = lista_tabelas2[0]
tabela.columns = tabela.iloc[0]
tabela[[0, 1]] = tabela["Variação percentual"].str.split(" ", expand=True)
tabela = tabela[1:9]
tabela = tabela.set_index("R$ milhões")
tabela.columns = tabela.iloc[0]
tabela=tabela[1:]
display(tabela)

nan,1T21,4T20,1T20,1T21/4T20 1T21/1T20,1T21/4T20,1T21/1T20
R$ milhões,,,,,,
"Receita de vendas, líquida",69.301,78.938,31.251,"-12,2% 121,8%","-12,2%","121,8%"
Custos e despesas,(27.359),(35.434),(21.619),"-22,8% 26,6%","-22,8%","26,6%"
Despesas relacionadas a Brumadinho,(637),(25.002),(708),"-97,5% -10,0%","-97,5%","-10,0%"
EBIT (LAJIR) ajustado,41.729,18.987,9.248,"119,8% 351,2%","119,8%","351,2%"
Margem EBIT ajustado (%),"60,2%","24,1%","29,6%","150,3% 103,5%","150,3%","103,5%"
EBITDA (LAJIDA) ajustado,45.741,23.492,12.924,"94,7% 253,9%","94,7%","253,9%"
Lucro líquido atribuído aos acionistas da Vale,30.564,4.825,984,"533,5% n.m.","533,5%",n.m.

In [32]:
tabela = lista_tabelas2[0]
tabela.columns = tabela.iloc[0]
tabela[[0, 1]] = tabela["Variação percentual"].str.split(" ", expand=True)
tabela = tabela[1:9]
tabela = tabela.set_index("R$ milhões")
tabela.columns = tabela.iloc[0]
tabela = tabela.drop("1T21/4T20 1T21/1T20", axis=1)
display(tabela)

nan,1T21,4T20,1T20,1T21/4T20,1T21/1T20,1T21/4T20,1T21/1T20
R$ milhões,,,,,,,
NaN,1T21,4T20,1T20,1T21/4T20,1T21/1T20,1T21/4T20,1T21/1T20
"Receita de vendas, líquida",69.301,78.938,31.251,"-12,2%","121,8%","-12,2%","121,8%"
Custos e despesas,(27.359),(35.434),(21.619),"-22,8%","26,6%","-22,8%","26,6%"
Despesas relacionadas a Brumadinho,(637),(25.002),(708),"-97,5%","-10,0%","-97,5%","-10,0%"
EBIT (LAJIR) ajustado,41.729,18.987,9.248,"119,8%","351,2%","119,8%","351,2%"
Margem EBIT ajustado (%),"60,2%","24,1%","29,6%","150,3%","103,5%","150,3%","103,5%"
EBITDA (LAJIDA) ajustado,45.741,23.492,12.924,"94,7%","253,9%","94,7%","253,9%"
Lucro líquido atribuído aos acionistas da Vale,30.564,4.825,984,"533,5%",n.m.,"533,5%",n.m.